runtime: python27
api_version: 1
threadsafe: yes

handlers:
    - url: /([a-z0-9.]+(\.js|\.css|\.ico))$
      secure: always
      redirect_http_response_code: 301
      static_files: dist/\1
      upload: dist/.*
    - url: /assets/.*
      secure: always
      redirect_http_response_code: 301
      static_files: dist/assets/\1
      upload: dist/assets/.*
    - url: /.*
      secure: always
      redirect_http_response_code: 301
      static_files: dist/index.html
      upload: dist/index.html
    - url: /
      static_dir: dist

skip_files:
    - (?!^dist)
