runtime: python27
api_version: 1
threadsafe: yes

handlers:
    - url: /
      static_files: dist/human-resources-app/index.html
      upload: dist/human-resources-app/index.html
    - url: /
      static_dir: dist/human-resources-app

skip_files:
    - e2e/
    - node_modules/
    - src/
    - ^(.*/)?\..*$
    - ^(.*/)?.*\.json$
    - ^(.*/)?.*\.md$
    - ^(.*/)?.*\.yaml$
    - ^LICENSE
